### ISSUE TITLE
PDF: REQUIRES and EXAMPLE tags in SNIPPETS ignored

### ISSUE THREAD

**Issue by martin-henz** [source-academy/sicp#94]
<img width="664" alt="Screenshot 2019-07-02 at 11 02 31 AM" src="https://user-images.githubusercontent.com/30220768/60479605-064b6d00-9cb9-11e9-9b71-854b46f638a7.png">

This program in PDF leads to:

<img width="401" alt="Screenshot 2019-07-02 at 11 04 27 AM" src="https://user-images.githubusercontent.com/30220768/60479661-2f6bfd80-9cb9-11e9-90be-dce5df0624e8.png">

but should include the example and the `cube` function. (This example is from section 1.3.1.)

**Comment by gerhean** [comment]
Fixed

**Comment by martin-henz** [comment]
Not quite fixed:

The link to sqrt in the PDF text 

<img width="744" alt="Screenshot 2019-07-04 at 9 46 35 PM" src="https://user-images.githubusercontent.com/30220768/60671256-4a02ca00-9ea5-11e9-9d9a-9fea256822ef.png">

goes to 

https://sourceacademy.nus.edu.sg/playground#chap=4&prgrm=GYVwdgxgLglg9mABAZwI4CcoAoAeBKRAbwChEzF0BTKEdJNTAfRikvSwEYAaRfAbmIBfYsQbYAnHj5A

whereas the corresponding link in the web edition goes to:

https://sourceacademy.nus.edu.sg/playground#chap=1&prgrm=FAMwrgdgxgLglgewgAgIYCMDOAKAHgSmQG9hkzkAnAUxjApV2QD4BeZABmQH5lGAuZAFpcAbmABfUuWkzyoSLEQpMARzCpqeQiWnVa9XsgBUvMZNkW54aPCTIA5ggQATAPpUICMPYAW2e2BUmJgANLzaUmR6dCgYOKrqmgFBmISC4cgAPBwAdOzsAIxmkZYy8jZKaABuVBSo9lR4IQCeEbo0Mch4yADUyK3IAPTIAEzFpWXWinZwALYADhQINf6BwWEExCXRBqg1dQ2rKRtDDmup46Xl08oqFDCucDC1R+sZOuQ7KI4u7p7efmSbwIJQsPCBmFBsgEqnuj2eFGwc0Wy0aEI2+Axlwm0mutlu9y0W3a+gJDyeLwKWIkwGAsJg2AAnPgxDiLMAgA

because it REQUIRES all the other functions.

**Comment by gerhean** [comment]
fix
